### ISSUE TITLE
Exception when adding an object with non ascii characters to the simulation.

### ISSUE THREAD

**Issue by ndrs92** [ndrs92/DesignSPHysics#21]
Only seen in Windows.

In a case with already created objects, adding a Wedge makes some of the object table items to go blank. No exceptions at all.

**Comment by ndrs92** [comment]
Already reproduce. It happens when non-english characters are introduced, like "Cuña"

Exception:

`Traceback (most recent call last):
  File "/home/ndrs/.FreeCAD/Mod/DesignSPHysics/DesignSPHysics.py", line 4136, in add_object_to_sim
    on_tree_item_selection_change()
  File "/home/ndrs/.FreeCAD/Mod/DesignSPHysics/DesignSPHysics.py", line 4373, in on_tree_item_selection_change
    object_name=context_object.Label)
  File "/home/ndrs/.FreeCAD/Mod/DesignSPHysics/dsphfc/dsphwidgets.py", line 2331, in __init__
    self.name_label = QtGui.QLabel(str(object_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 2: ordinal not in range(128)`

**Comment by ndrs92** [comment]
Fixed in a4fbc05a18fe824e3844f93fead5400fe7185ada
